name: Build Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * 1'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"
      - run: |
          go version
          go mod download
          CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gcpcc .
      - uses: actions/upload-artifact@v2
        with:
          name: gcpcc
          path: gcpcc
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/dacbd/gcpcc:latest
